---
title: "Iteration and listcols"
author: "Catherine"
date: "10/30/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

set.seed(1)
```


#### for loop
```{r for loops}
df = data_frame( # creat a data frame
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

is.list(df)

df[[2]]
```

```{r function}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  tibble(
  mean_x = mean(x),
  sd_x = sd(x)
  )

}


```
apply the function
```{r}
mean_and_sd(df[[1]])
mean_and_sd(df[[2]])
mean_and_sd(df[[3]])
mean_and_sd(df[[4]])
```

```{r}
output = vector("list", length = 4)

output[[1]] = mean_and_sd(df[[1]])
output[[2]] = mean_and_sd(df[[2]])
output[[3]] = mean_and_sd(df[[3]])
output[[4]] = mean_and_sd(df[[4]])

for (i in 1:4) {
  output[[i]] = mean_and_sd(df[[i]])
}

output
```

replace the 'for' loop with 'map'
```{r map statement}
output_map = map(df, mean_and_sd)
output_map
```

Try a different function
```{r}
output_med = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = median(df[[i]])
}

output_med = map_dbl(df, median) # map_df 
output_med
```
#### code syntax
be clear about arguements
```{r}
output = map(.x = df, ~ mean_and_sd(x = .x)) # it is different from the x in function mean_and_sd
```

```{r}
library(rvest)
read_page_reviews <- function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  data_frame(title, stars, text)
}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base, 1:5)

# for loop

output = vector("list", 5)

for (i in 1:5) {
  output[[i]] = read_page_reviews(vec_urls[[i]])
}
dynamite_reviews = bind_rows(output)

# map
output_review = map_df(.x = vec_urls, read_page_reviews)
```


```{r rnoaa example}
library(rnoaa)

weather = 
  meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}

```


